FROM python:3.12-slim as builder

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
  pip install --default-timeout=1000 torch --index-url https://download.pytorch.org/whl/cpu && \
  pip install --default-timeout=1000 -r requirements.txt


FROM python:3.12-slim

WORKDIR /app
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


ENV HF_HOME=/app/model_cache
ENV SENTENCE_TRANSFORMERS_HOME=/app/model_cache

COPY --from=builder /opt/venv /opt/venv

COPY . .
RUN python -c "from sentence_transformers import SentenceTransformer, CrossEncoder; SentenceTransformer('all-MiniLM-L6-v2'); CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')"



RUN mkdir -p /app/data /app/logs /app/LocalState && \
chmod -R 755 /app/data /app/logs /app/LocalState


RUN useradd -u 8888 appuser && chown -R appuser:appuser /app
USER appuser


CMD ["python", "application/discordApp/bot.py"]